### ISSUE TITLE
Env Vars?

### ISSUE THREAD

**Issue by chriscoyier** [BendJS/simple-website#24]
If we pull this now and try to run it, we're stopped by:

<img width="985" alt="Screenshot 2023-05-26 at 4 19 10 PM" src="https://github.com/BendJS/simple-website/assets/69156/6812b784-92d3-4b0c-b98f-ade307f8b9ed">

What's the strategy there? Can there be "public" Sanity keys?

**Comment by nslee333** [comment]
`NEXT_PUBLIC` is Next's required prefix for environment variables.

Why Next / Vercel calls it `public` doesn't make sense to me because according to the docs:

`
By default environment variables are only available in the Node.js environment, meaning they won't be exposed to the browser.
`

[NextJS Source](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#exposing-environment-variables-to-the-browser)

**Comment by ctsstc** [comment]
I imagine once this is integrated https://github.com/BendJS/simple-website/pull/29 this ticket will no longer be relevant?

**Comment by chriscoyier** [comment]
yah this was an old site thing
