### ISSUE TITLE
Do we want to take out the member spotlight?

### ISSUE THREAD

**Issue by nslee333** [BendJS/simple-website#30]
Since It's kinda difficult to keep up with every month. It was fun to throw in when I was revamping it, but I'm not sure if it's good idea anymore. I can write the pr if everyone agrees.

**Comment by nslee333** [comment]
@chriscoyier @ctsstc @kcloud99 @CalebJamesStevens

**Comment by chriscoyier** [comment]
I'd probably remove it since it's really never changed and there is no mechanism in place to update it with new members. 

It's still a cool idea though, it just needs more thought and work to pull off. Putting in on the website is probably the *last* step, not the first. 

Could it be replaced with something else interesting? Perhaps a more emphasized section to send people over to the YouTube history? Or, instead of a member spotlight that is like photo/name/paragraph, it's just a list of names of regular members that have something they want to link to? e.g. our personal websites (like me) or GitHub (e.g. Robert https://github.com/broofa), or podcast like Kyle is doing, etc?

**Comment by nslee333** [comment]
The regular members idea would be cool, and it would take less maintenance than a member spotlight. If we can get a rough list going I can throw a design together.

**Comment by ctsstc** [comment]
It could also be utilized for an organizers section. I think Kyle had plans on trying to split out details of the meetup to additional folks as co-organizers, so it may start off a bit empty but would hopefully have more folks later on.

It would be great to have a list of talks, but that requires someone to keep those up to date, and consistent in terms of what we'd showcase.

**Comment by nslee333** [comment]
I think it's probably best to keep it as low maintenance as possible since we're all very busy with our own projects. I'll throw together a PR to at least take it down from what's being displayed, I'll leave the component intact so someone can use that as a frame for changes in the future.
